Home page contents
AbenezerKb/personal-portfolio-site pull request #2
Opened 2022-08-18 08:59 UTC by AbenezerKb

In this PR, I :

- [ ] set up a "personal portfolio site" repository
- [ ] Created a new branch called "home_page_contents", according to the GitHub flow
- [ ] Added a .gitignore file.
- [ ] Set up a linter for HTML and CSS
- [ ] Added a descriptive README file to your project
- [ ] Added 3 files (each one in a separate commit):
- [ ] 1. A .html file that includes home page of the portfolio 
- [ ] 2. B .css file in mobile first format
- [ ] 3. C modified .css file for the desktop format
- [ ] 4. D test.md file with the text "This file should be ignored by git".

2022-08-18 09:44 UTC, Ugboaja-Uchechi requested changes
Hi @AbenezerKb, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- Linters are passing ✔️ 
- README is descriptive 👍 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 09:44 UTC, Ugboaja-Uchechi commented on index.html
> +        <div class="humberger-container">
- [ ] Kindly change the `div` with a class of `main-container` to a `header` tag 🙏 . This would make your code semantic. You can read more about semantic HTML in [this article](https://www.w3schools.com/html/html5_semantic_elements.asp)

2022-08-18 09:44 UTC, Ugboaja-Uchechi commented on index.html
> +        <h3>My Logo</h3>
- [ ] Please wrap your logo in an `a` tag 🙏 . This would make your code semantic, and give a better user experience(UX)

2022-08-18 09:44 UTC, Ugboaja-Uchechi commented on style.css
> +    justify-content: space-around;
- [ ] Kindly give your website the appropriate margin and padding so it looks as close as possible to the Figma design 🙏 

Figma Design | Your Design
------------- | -------------
![image](https://user-images.githubusercontent.com/74814780/185363268-9cbecf6b-bd4b-4614-80ad-1ca5265cafe1.png)  |  ![image](https://user-images.githubusercontent.com/74814780/185363192-156973de-3bcd-47cb-8bf1-29cc8b1d667b.png)

2022-08-18 09:44 UTC, Ugboaja-Uchechi commented on index.html
> +
- [ ] Kindly change the `div` with a class of `body-container` to a `section` tag 🙏 . This would make your code semantic. You can read more about semantic HTML in [this article](https://www.w3schools.com/html/html5_semantic_elements.asp)

2022-08-18 09:44 UTC, Ugboaja-Uchechi commented on index.html
> +    <div class="name">I'm Abenezer  Glad to see You!</div>
- [ ] Kindly change the `div` with a class of `name` to an `h1` tag 🙏 . This would make your code semantic and help with SEO. You can read more about semantic HTML in [this article](https://www.w3schools.com/html/html5_semantic_elements.asp)

2022-08-18 09:44 UTC, Ugboaja-Uchechi commented on index.html
> +    </div>
- [ ] Kindly change the `div` with a class of `detail` to a `p` tag 🙏 . This would make your code semantic and help with SEO. You can read more about semantic HTML in [this article](https://www.w3schools.com/html/html5_semantic_elements.asp)

2022-08-18 09:44 UTC, Ugboaja-Uchechi commented on index.html
> +     <a href="#" target=”_blank”> <img src="./angellist.svg" alt="angellist icon">   </a>
- [ ] Great job wrapping them in an `a` tag 👍 . Kindly wrap the icon images in a `ul` tag and each of them should be in a `li` tag 🙏

2022-08-18 09:44 UTC, Ugboaja-Uchechi commented on index.html
> +    </div>
- [ ] Kindly change the `div` with a class of `social-media-connect` to an `h` tag 🙏 . This would make your code semantic and help with SEO. You can read more about semantic HTML in [this article](https://www.w3schools.com/html/html5_semantic_elements.asp)

2022-08-18 10:15 UTC, AbenezerKb commented on index.html
> +        <div class="humberger-container">
changing it header wouldn't make it right. I used the main-container in order to classify it in the body

2022-08-18 11:15 UTC, AbenezerKb commented on style.css
> +    justify-content: space-around;
@Ugboaja-Uchechi please review it and give comment if it still doesn't satisfy

2022-08-18 13:51 UTC, omarsalem7 requested changes
Hi @AbenezerKb, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![Almost near](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

 ## Highlights
✔️ All linter checks pass.
✔️ Descriptive pull request.
✔️ Good descriptive readme.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 13:51 UTC, omarsalem7 commented on index.html
> +    </nav>
- [ ] As stated by the previous reviewer, kindly wrap your nav with a header tag because the header tag is used as a page header, it contains the site's title or logo and the main site navigation [Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header) for more info.[Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header) for more info.

- [ ] [OPTIONAL] It will be better if you remove the wrapper div with class `main-container` and make `<header>` and `<section>`  to make your project structure well and also improve SEO for it. Your structure will be something like the following image.
> ![image](https://user-images.githubusercontent.com/53402600/185409717-b482ca3e-1e07-49bc-9a93-4d90f93067f9.png)

2022-08-18 13:51 UTC, omarsalem7 commented on index.html
> +</section>
- [ ] As stated before kindly add appropriate margin and padding to match your design like figma.

| Your design @375px (mobile version- ex: iPhone 6/7/8)  | Figma design|
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/53402600/185410468-9581e0a1-fb2d-4e23-9c22-cfdf21cab086.png)  | ![image](https://user-images.githubusercontent.com/53402600/185411050-69b8906d-d469-4d6f-8247-1af6b5fac590.png) |

2022-08-18 16:58 UTC, bobb-Rob requested changes
Hi @AbenezerKb , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

 ## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)
✅ Neat Commit messages


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 16:58 UTC, bobb-Rob commented on index.html
> +</section>
- [ ] As pointer out by the previous reviewer, your current design will need some `margin` and `padding`. Please see below my suggestions for implementation.
    - Add the following CSS code to `<section class="body-container">`:
    
          padding: 128px 1.5rem 1.5rem 1.5rem

This will create 128px space before the `h1` tag, create 1.5rem space at the right, bottom, and left of the `section` tag. 
For more about padding [read this MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/padding)

2022-08-18 16:58 UTC, bobb-Rob commented on index.html
> +    <header>
In line with the previous reviewers [comment](https://github.com/AbenezerKb/personal-portfolio-site/pull/2/files#r949157318), in order to make your design look like the figma design given, please add the below CSS statement to the `header` tag. You can decide to declare a class name as the selector. Essentially, this gives a padding of 24px or 1.5rem to the `header` tag. 

![image](https://user-images.githubusercontent.com/84156714/185447172-654de8fd-ce44-49e5-ae69-03e2a229661b.png)

2022-08-18 16:58 UTC, bobb-Rob commented on style.css
> +  }
Refer to my previous comment about adding padding to this class selector.

2022-08-18 16:58 UTC, bobb-Rob commented on index.html
> +    <div class="social-media-left-space"></div>
- [ ] [OPTIONAL] The first image below is the Figma design and it does not have any left space. If you take `<div class="social-media-left-space"></div>` off your HTML and kindly add `padding-right: 20px` to the `<li>` tags, your design will look better. The second image is your design.

![image](https://user-images.githubusercontent.com/84156714/185450059-53ffff16-3990-4b65-9f51-3fc8ce606998.png) 

![image](https://user-images.githubusercontent.com/84156714/185450127-14f3e03c-f65f-4739-b7fc-404f4cfb3127.png)

2022-08-19 10:38 UTC, topeogunleye approved these changes
### Hi @AbenezerKb, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
>
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Followed Github flow :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good description summary :heavy_check_mark:
 
## [Optional] suggestions:
- [ ]  Next time, and for future commits, I kindly suggest that you please make use of imperative mood in the subject line for your commit messages.
:x: Bad Commit Messages :x:
<img width="268" alt="image" src="https://user-images.githubusercontent.com/52934128/185601166-08e955ee-a323-433d-819c-56a95aec11aa.png">
### ✔️ Good Commit Messages: ✔️
✔️  Add fix for dark mode toggle state
✔️  Update README file.
✔️  Add styles to h1.

- [ ] Please refer to this article: please read it and apply it in your work from now on: [Professional repo - basic rules](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md);
 
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-19 10:41 UTC, merged